<?php
$CFG = array (
  'charsets' => 'cp1251 utf8 latin1',
  'lang' => 'uk',
  'time_web' => '600',
  'time_cron' => '600',
  'backup_path' => 'backup/',
  'backup_url' => 'backup/',
  'only_create' => 'MRG_MyISAM MERGE HEAP MEMORY',
  'globstat' => 0,
  'my_host' => '172.120.123.178',
  'my_port' => '3306',
  'my_user' => 'h24_news',
  'my_pass' => 'h24_news',
  'my_comp' => 0,
  'my_db' => 'h24_news',
  'auth' => 'mysql cfg',
  'user' => '',
  'pass' => '',
  'confirm' => '30',
  'exitURL' => './',
  'outfile_path' => 'backup/',
  'outfile_size' => '64',
);
?>